name: dofen
model:
  name: dofen
  m: 16
  d: 4
  n_head: 4  # default 1
  n_forest: 100
  n_hidden: 128
  dropout: 0.0
  categorical_optimized: false
  fast_mode: 2048
  use_bagging_loss: false
  norm: layer_norm
data:
  target_transform: false
trainer:
  lr: 1e-3
  save_model: false
  early_stop_patience: 1000
